language: ruby
sudo: required
notifications:
  email: false
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
services:
  - mysql
  - postgresql
env:
  matrix:
    - DB=pg
    - DB=mysql
    - DB=sqlite
before_script:
  # PG and mysql is simpler.
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS fast_inserter;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'create database fast_inserter;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS fast_inserter;'; fi"
