language: ruby
sudo: required
notifications:
  email: false
rvm:
  - 2.4.5
  - 2.5.3
  - 2.6.2
  - 2.7.2
  - ruby-head
env:
  matrix:
    - DB=pg
    - DB=mysql
    - DB=sqlite
before_script:
  # PG and mysql is simpler.
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS fast_inserter;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'create database fast_inserter;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS fast_inserter;'; fi"
