sqlite:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500
mysql:
  adapter: mysql2
  database: fast_inserter
  username: root
  password: root
  encoding: utf8
pg:
  adapter: postgresql
  database: fast_inserter
  username: postgres
  password: postgres_password
  host: localhost
