name: Ruby

on: [push, pull_request]

jobs:
  # label of the container job
  postgres-job:
    runs-on: ubuntu-latest

    container: ubuntu:latest

    strategy:
      matrix:
        # ruby-version: ['2.4.0', '2.5.1', '2.6.6', '2.7.2', 'ruby-head']
        ruby-version: ['ruby-head']
    
    services:
      postgres:
        image: postgres:latest
        # service environment variables
        # `POSTGRES_HOST` is `postgres`
        env:
          # optional (defaults to `postgres`)
          POSTGRES_DB: postgres_db
          # required
          POSTGRES_PASSWORD: postgres_password
          # optional (defaults to `5432`)
          POSTGRES_PORT: 5432
          # optional (defaults to `postgres`)
          # POSTGRES_USER: postgres_user
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      # queries database with postgres client
      - name: Query database
        run: psql -h postgres -d postgres_db -U postgres -c 'SELECT 1;'
        env:
          # postgress password is required; alternatively, you can run:
          # `PGPASSWORD=postgres_password psql ...`
          PGPASSWORD: postgres_password
      - name: Set up Database
        run: psql -h postgres -c 'DROP DATABASE IF EXISTS fast_inserter;' -U postgres && psql -h postgres -c 'create database fast_inserter;' -U postgres
      - name: Set up Ruby
        # Lock to this commit, v1.82.0
        uses: ruby/setup-ruby@5e4f0a10bfc39c97cd5358121291e27e5d97e09b
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake

