name: Ruby

on: push

jobs:
  sqlite-job:
    runs-on: ubuntu-20.04

    env:
      DB: sqlite

    strategy:
      matrix:
        # ruby-version: ['2.4.0', '2.5.1', '2.6.6', '2.7.2', 'ruby-head']
        ruby-version: ['ruby-head']
    
    steps:      
      - name: Checkout
        # Pin to this commit: v2
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Build and Test
        uses: ./.github/actions/ruby-steps
        
  postgres-job:
    runs-on: ubuntu-20.04

    env:
      DB_HOST: localhost
      DB: pg
  
    strategy:
      matrix:
        # ruby-version: ['2.4.0', '2.5.1', '2.6.6', '2.7.2', 'ruby-head']
        ruby-version: ['ruby-head']
    
    services:
      postgres:
        # Pin to this commit: version 14.0
        image: postgres@sha256:2b8a60d4ae4b3cf9dc5ae823700f699fdabdb0d03901dd480c9a410ca72c4571
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        # Pin to this commit: v2
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Set up Database
        run: psql -h localhost -c 'DROP DATABASE IF EXISTS fast_inserter;' -U postgres && psql -h localhost -c 'create database fast_inserter;' -U postgres
        env:
          PGPASSWORD: postgres_password
      - name: Build and Test
        uses: ./.github/actions/ruby-steps

  # mysql-job:
  #   runs-on: ubuntu-20.04

  #   # env:
  #   #   DB_USER: root
  #   #   DB_PASSWORD: 'root'
  #   #   DB_HOST: localhost
  #   env:
  #     DB_HOST: localhost
  #     DB: mysql

  #   strategy:
  #     matrix:
  #       # ruby-version: ['2.4.0', '2.5.1', '2.6.6', '2.7.2', 'ruby-head']
  #       ruby-version: ['ruby-head']
    
  #   # services:
  #   #   mysql:
  #   #     # Pin to this commit: version 8.0.26
  #   #     image: mysql@sha256:a0a2699fe9133b68079099740338691e72e0f880325e28f1b1bdb7589d6a5be1
  #   #     env:
  #   #       MYSQL_ALLOW_EMPTY_PASSWORD: yes
  #   #       MYSQL_DATABASE: fast_inserter
  #   #     ports:
  #   #       - 3306:3306
  #   #     options: >-
  #   #       --health-cmd="mysqladmin ping"
  #   #       --health-interval 10s
  #   #       --health-timeout 5s
  #   #       --health-retries 5

  #   steps:
  #     # Pin to this commit: v2
  #     - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
  #     - name: Set up Database
  #       run: |
  #         sudo systemctl start mysql.service
  #         sudo mysql -h 127.0.0.1 -e 'create database IF NOT EXISTS fast_inserter;'
  #     - name: Set up Ruby
  #       # Pin to this commit: v1.82.0
  #       uses: ruby/setup-ruby@5e4f0a10bfc39c97cd5358121291e27e5d97e09b
  #       with:
  #         ruby-version: ${{ matrix.ruby-version }}
  #         bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  #     - name: Run tests
  #       run: bundle exec rake
