name: Ruby

on: push

env:
  DB_HOST: localhost

jobs:
  # label of the container job
  postgres-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['2.4.0', '2.5.1', '2.6.6', '2.7.2', 'ruby-head']
    
    services:
      postgres:
        # Pint to this commit of 14.0
        image: postgres:@sha256:2b8a60d4ae4b3cf9dc5ae823700f699fdabdb0d03901dd480c9a410ca72c4571
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Pin to this commit: v2
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Set up Database
        run: psql -h localhost -c 'DROP DATABASE IF EXISTS fast_inserter;' -U postgres && psql -h localhost -c 'create database fast_inserter;' -U postgres
        env:
          PGPASSWORD: postgres_password
      - name: Set up Ruby
        # Pin to this commit: v1.82.0
        uses: ruby/setup-ruby@5e4f0a10bfc39c97cd5358121291e27e5d97e09b
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run tests
        run: bundle exec rake

